---
- name: Retrieve Cisco IOS Facts
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Gather Cisco IOS Facts
      cisco.ios.ios_facts:
    - name: Display Version
      ansible.builtin.debug:
        msg: "{{ ansible_net_version }}"
    - name: Display Serial Number
      ansible.builtin.debug:
        msg: "{{ ansible_facts['net_serialnum'] }}"