---
- name: Retrieve the cisco ios facts and cisco ios network version
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
    - name: Print the IOS version
      ansible.builtin.debug:
        msg: "{{ ansible_facts['net_version'] }}"
