---
- name: Gather a subset of the cisco network device configuration (Layer 3 interfaces only) and verify the ip address information is accurate and config did not changed.
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Gather cisco network device configuration
      cisco.ios.ios_facts:
        gather_subset:
          - "!all"
          - "!min"
          - interfaces
    - name: Verify ip address information is accurate and config did not changed
      ansible.builtin.assert:
        that: "{{ ansible_net_interfaces | dict2items }}"