- name: Update cisco ios vlan
  hosts: cisco
  gather_facts: false
  tasks:
    - name: Gather cisco ios facts
      cisco.ios.ios_facts:
        gather_subset: all
    - name: Update cisco ios vlan
      cisco.ios.ios_config:
        lines: "{{ vlans }}"
        parents: "{{ vlans }}"